---
cops_deploy_ssh_key_paths:
  # replace by your env id used in the host definition inside your former inventory
  deploy:
    path: "{{'{{'}}'local/.ssh/deploy'|copsf_abspath}}"
    pub: |-
      ssh-rsa xxx deploy
    private: |-
      -----BEGIN RSA PRIVATE KEY-----
      xxx
      -----END RSA PRIVATE KEY-----
cops_{{cookiecutter.app_type}}_registries:
- username: "userA"
  registry: "{{cookiecutter.docker_registry}}"
  password: "superpwd"
# cops_{{cookiecutter.app_type}}_sentry_dsn: ""
# cops_{{cookiecutter.app_type}}_mailcatcher_password: ""
{% if cookiecutter.with_ftp %}
cops_{{cookiecutter.app_type}}_ftp_password: secrettS6oU6sX5bI5wJ3y
{% endif %}
